---
- name: Install and configure nginx reverse proxy
  hosts: webservers
  become: yes

  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: latest
        update_cache: yes

    - name: Remove default nginx configuration
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Add nginx configuration
      copy:
        src: conf/reverse_proxy.conf
        dest: /etc/nginx/sites-available/reverse_proxy.conf
        owner: root
        group: root
        mode: '0644'

    - name: Enable website configuration
      file:
        src: /etc/nginx/sites-available/reverse_proxy.conf
        dest: /etc/nginx/sites-enabled/reverse_proxy.conf
        state: link

    - name: Test nginx configuration
      command: nginx -t
      changed_when: false

    - name: Restart nginx
      service:
        name: nginx
        state: restarted
        enabled: yes
